# Generated by Django 3.2.16 on 2023-05-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('project_type', models.TextField()),
                ('project_sub_type', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('registrant', models.TextField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='static/projectimages')),
                ('train_file', models.FileField(upload_to='')),
                ('test_file', models.FileField(upload_to='')),
                ('project_detail', models.TextField()),
            ],
        ),
    ]
