# Generated by Django 3.2.16 on 2023-09-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.TextField()),
                ('project_sub_type', models.TextField()),
                ('project_name', models.TextField()),
                ('registrant', models.TextField()),
                ('project_registration_date', models.DateTimeField(auto_now_add=True)),
                ('project_update_date', models.DateTimeField(auto_now=True)),
                ('project_explanation', models.TextField()),
                ('project_image', models.ImageField(blank=True, default='', upload_to='image/%Y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_file', models.FileField(default='', upload_to='file/project/%Y%m%d')),
                ('project_file_name', models.TextField()),
                ('project_file_size', models.TextField()),
                ('project_file_registration_date', models.DateTimeField(auto_now_add=True)),
                ('project_file_extension', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project')),
            ],
        ),
    ]
