# Generated by Django 3.2.16 on 2023-05-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project_file_extension',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
