# Generated by Django 3.2.16 on 2023-09-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.TextField()),
                ('process_type', models.TextField()),
                ('work_type', models.TextField()),
                ('input_value', models.TextField()),
                ('replace_value', models.TextField()),
                ('sort', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('mlmodel_id', models.ForeignKey(db_column='mlmodel_id', on_delete=django.db.models.deletion.CASCADE, related_name='mlmodel', to='mlmodel.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MLSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.TextField(blank=True, max_length=30)),
                ('feature_algorithm', models.TextField()),
                ('columns', models.TextField()),
                ('column_size', models.IntegerField(default=0)),
                ('split_algorithm', models.TextField()),
                ('split_rate', models.IntegerField()),
                ('k_value', models.IntegerField(default=0)),
                ('sampling_algorithm', models.TextField()),
                ('target', models.TextField()),
                ('mlmodel_id', models.ForeignKey(db_column='mlmodel_id', on_delete=django.db.models.deletion.CASCADE, related_name='mlmodel_info', to='mlmodel.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MLDatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('dataset_file', models.FileField(default='', upload_to='file/dataset/%Y%m%d')),
                ('dataset_file_extension', models.TextField()),
                ('mlmodel_id', models.ForeignKey(db_column='mlmodel_id', on_delete=django.db.models.deletion.CASCADE, related_name='mlmodel_rel_id', to='mlmodel.mlmodel')),
            ],
        ),
    ]
