# Generated by Django 3.2.16 on 2023-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=30)),
                ('column_name', models.TextField()),
                ('process_type', models.TextField()),
                ('work_type', models.TextField()),
                ('input_value', models.TextField()),
                ('replace_value', models.TextField()),
                ('sort', models.IntegerField()),
            ],
        ),
    ]
