# Generated by Django 3.2.16 on 2023-04-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=30)),
                ('feature_algorithm', models.TextField()),
                ('columns', models.TextField()),
                ('split_algorithm', models.TextField()),
                ('split_rate', models.IntegerField()),
                ('k_value', models.IntegerField()),
                ('sampling_algorithm', models.TextField()),
            ],
        ),
    ]
