# Generated by Django 3.2.16 on 2023-04-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0002_mlsampling'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlsampling',
            name='column_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mlsampling',
            name='k_value',
            field=models.IntegerField(default=0),
        ),
    ]
