# Generated by Django 3.2.16 on 2023-09-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
                ('best_accuracy', models.FloatField(blank=True, null=True)),
                ('best_recall', models.FloatField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='project.project')),
            ],
        ),
    ]
