# Generated by Django 3.2.16 on 2023-09-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.TextField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('confusion_matrix', models.TextField(blank=True, null=True)),
                ('features_importance', models.TextField(blank=True, null=True)),
                ('Provability', models.FloatField(blank=True, null=True)),
                ('Prediction', models.FloatField(blank=True, null=True)),
                ('Favorite', models.BooleanField(default=False)),
                ('mlmodel_id', models.ForeignKey(db_column='mlmodel_id', on_delete=django.db.models.deletion.CASCADE, related_name='mlmodel_id', to='mlmodel.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MlParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.TextField()),
                ('parameter_name', models.TextField()),
                ('parameter_value', models.TextField()),
                ('model_learning_id', models.ForeignKey(db_column='model_learning_id', on_delete=django.db.models.deletion.CASCADE, related_name='model_learning_id', to='learning.modellearning')),
            ],
        ),
    ]
